return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	opts = {
		highlight = { enable = true },
		indent = { enable = true },
		cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
		ensure_installed = {
			"bash",
			"c",
      			"diff",
      			"html",
      			"javascript",
			"typescript",	
      			"tsx",
      			"jsdoc",
      			"json",
      			"jsonc",
      			"lua",
      			"luadoc",
      			"luap",
      			"markdown",
      			"markdown_inline",
      			"python",
      			"query",
      			"regex",
      			"toml",
      			"xml",
      			"yaml",
			"wgsl",
			"wgsl_bevy",
		},
	},
}
