#!/usr/bin/env bash

get_title () {
    echo $(mpc --format "%title%" current)
}

get_artist () {
	echo $(mpc --format "%artist%" current)
}

get_cover () {
	File=$(mpc --format "%file%" current)
    	Music_dir="$HOME/Music"

    	Full_path="$Music_dir/$File"

	Temp_file=$(mktemp /dev/shm/cover.XXXXXX)
	ffmpeg -y -i "$Full_path" -an -f image2pipe -vcodec mjpeg - 2>/dev/null > $Temp_file

	echo $Temp_file

	nohup bash -c "sleep 1; rm '$Temp_file'" >/dev/null 2>&1 &
}

get_status () {
    status=$(mpc status | grep -oE "\[playing\]|\[paused\]")
    echo "${status#[}" | tr -d "]"
}

case "$1" in
    --title) get_title ;;
    --artist) get_artist ;;
    --cover) get_cover ;;
    --status) get_status ;;
esac
